# Essentials
vo=gpu-next
gpu-api=opengl
gpu-context=wayland
hwdec=auto-safe

fbo-format=rgba8
dither=no
gpu-next=no
# Smoothmotion
interpolation=yes
tscale=oversample
video-sync=display-resample

# QoL
keep-open=yes
save-position-on-quit=yes
autofit-larger=80%x80%

# UOSC
osd-bar=no
border=no
