package db

var DefaultExerciseTemplates = []ExerciseTemplateSeed{
	{ID: 1, Title: "Machine Preacher Curl", DefaultSetCount: 3, LateralType: "UNILATERAL", MuscleGroup: "BICEPS"},
	{ID: 2, Title: "Dumbbell Preacher Curl", DefaultSetCount: 3, LateralType: "UNILATERAL", MuscleGroup: "BICEPS"},
	{ID: 3, Title: "Cable Hammer Curl", DefaultSetCount: 3, LateralType: "BILATERAL", MuscleGroup: "FOREARMS"},
	{ID: 4, Title: "Dumbbell Hammer Curl", DefaultSetCount: 0, LateralType: "BILATERAL", MuscleGroup: "FOREARMS"},
	{ID: 5, Title: "Triceps Extension", DefaultSetCount: 0, LateralType: "UNILATERAL", MuscleGroup: "TRICEPS"},
	{ID: 6, Title: "Triceps Extension", DefaultSetCount: 0, LateralType: "BILATERAL", MuscleGroup: "TRICEPS"},
	{ID: 7, Title: "Lat Pulldown", DefaultSetCount: 0, LateralType: "BILATERAL", MuscleGroup: "LATS"},
	{ID: 8, Title: "Wide Row", DefaultSetCount: 0, LateralType: "BILATERAL", MuscleGroup: "UPPER_BACK"},
	{ID: 9, Title: "Seated Leg Curl", DefaultSetCount: 0, LateralType: "BILATERAL", MuscleGroup: "HAMSTRINGS"},
	{ID: 10, Title: "Calf Press", DefaultSetCount: 0, LateralType: "BILATERAL", MuscleGroup: "CALVES"},
	{ID: 11, Title: "Leg Extension", DefaultSetCount: 0, LateralType: "BILATERAL", MuscleGroup: "QUADS"},
	{ID: 12, Title: "Leg Press", DefaultSetCount: 0, LateralType: "BILATERAL", MuscleGroup: "QUADS"},
	{ID: 13, Title: "Pec Dec Elbow Pad", DefaultSetCount: 0, LateralType: "BILATERAL", MuscleGroup: "CHEST"},
	{ID: 14, Title: "Pec Dec", DefaultSetCount: 0, LateralType: "BILATERAL", MuscleGroup: "CHEST"},
	{ID: 15, Title: "Chest Press Decline", DefaultSetCount: 0, LateralType: "BILATERAL", MuscleGroup: "CHEST"},
	{ID: 16, Title: "Chest Press", DefaultSetCount: 0, LateralType: "BILATERAL", MuscleGroup: "CHEST"},
	{ID: 17, Title: "Cable Lateral Raise", DefaultSetCount: 0, LateralType: "UNILATERAL", MuscleGroup: "SHOULDERS"},
	{ID: 18, Title: "Garhammer", DefaultSetCount: 0, LateralType: "BILATERAL", MuscleGroup: "CORE"},
	{ID: 19, Title: "Preacher Curl", DefaultSetCount: 3, LateralType: "BILATERAL", MuscleGroup: "BICEPS"},
	{ID: 20, Title: "Hammer Curl", DefaultSetCount: 3, LateralType: "BILATERAL", MuscleGroup: "FOREARMS"},
	{ID: 21, Title: "Gym 80 Lat Row", DefaultSetCount: 0, LateralType: "BILATERAL", MuscleGroup: "LATS"},
	{ID: 22, Title: "T-Bar Row", DefaultSetCount: 0, LateralType: "BILATERAL", MuscleGroup: "UPPER_BACK"},
	{ID: 23, Title: "Ab Crunch", DefaultSetCount: 0, LateralType: "BILATERAL", MuscleGroup: "CORE"},
	{ID: 24, Title: "Smith Machine 30 Deg", DefaultSetCount: 0, LateralType: "BILATERAL", MuscleGroup: "CHEST"},
	{ID: 25, Title: "Dumbbell Lateral Raise", DefaultSetCount: 0, LateralType: "UNILATERAL", MuscleGroup: "SHOULDERS"},
	{ID: 26, Title: "Hack Squat", DefaultSetCount: 0, LateralType: "BILATERAL", MuscleGroup: "QUADS"},
}
