set -g default-command /bin/fish
set -g default-shell /bin/fish
set -g extended-keys on
set -g extended-keys-format csi-u
set -a terminal-features "tmux-256color:RGB"
set -g prefix C-SPACE
set -g base-index 1
set -g renumber-windows on   
set -g mode-keys vi
set -g status-position top
set -g status-justify absolute-centre
set -g status-style "bg=default"
set -g window-status-current-style "fg=blue bold"
set -g status-left-length 25

set -g status-interval 5
set -g status-right '#{?client_prefix, _ ,}%a %b %d, %H:%M'
set -g status-left "#S"


bind r source-file "~/.config/tmux/tmux.conf"
bind b set -g status
bind f run "tmux neww ~/.config/scripts/tmux-session-dispensary.sh"
bind N run "~/.config/scripts/tmux-session-dispensary.sh ~/notes"
bind P run "~/.config/scripts/tmux-session-dispensary.sh ~/repos"
bind D run "~/.config/scripts/tmux-session-dispensary.sh ~/.config"
bind H run "~/.config/scripts/tmux-session-dispensary.sh ~"
bind c neww -c "#{pane_current_path}"
bind G run "~/.config/scripts/open-github.sh"
bind g neww -n "git" -c "#{pane_current_path}" lazygit
