general {
    lock_cmd = pidof hyprlock || $HOME/.config/rofi/scripts/time-tracker.sh lock  # pause tracker while locked.
    before_sleep_cmd = loginctl lock-session       # lock before suspend.
}

listener {
    timeout = 300                                   # 5min.
    on-timeout = brightnessctl -s set 10            # dim backlight, avoid 0 on OLED.
    on-resume = brightnessctl -r                    # restore backlight.
}

listener {
    timeout = 305                                   # 5min.
    on-timeout = brightnessctl -d platform::kbd_backlight set 0   # turn off keyboard backlight.
    on-resume  = brightnessctl -d platform::kbd_backlight set 1   # turn on keyboard backlight.
}

listener {
    timeout = 305                                   # 5min.
    on-timeout = loginctl lock-session              # lock screen.
}

listener {
    timeout = 305                                   # 5min.
    on-timeout = niri msg action power-off-monitors           # screen off.
    on-resume = niri msg action power-on-monitors && brightnessctl -r  # screen on + restore brightness.
}

listener {
    timeout = 1800                                  # 30min.
    on-timeout = $HOME/.config/rofi/scripts/time-tracker.sh systemctl-break suspend-then-hibernate  # stop/restart tracker around suspend.
}
